/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as CareersRouteImport } from "./routes/careers";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as EnrollRouteImport } from "./routes/enroll";
import { Route as FaqRouteImport } from "./routes/faq";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as PlansRouteImport } from "./routes/plans";
import { Route as CoursesIndexRouteImport } from "./routes/courses.index";
import { Route as CoursesSlugRouteImport } from "./routes/courses.$slug";
import { Route as LegalGuidelinesRouteImport } from "./routes/legal.guidelines";
import { Route as LegalPrivacyRouteImport } from "./routes/legal.privacy";
import { Route as LegalRefundsRouteImport } from "./routes/legal.refunds";
import { Route as LegalTermsRouteImport } from "./routes/legal.terms";
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
});
const CareersRoute = CareersRouteImport.update({
  id: "/careers",
  path: "/careers",
  getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const EnrollRoute = EnrollRouteImport.update({
  id: "/enroll",
  path: "/enroll",
  getParentRoute: () => rootRouteImport,
});
const FaqRoute = FaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const PlansRoute = PlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => rootRouteImport,
});
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: "/courses/",
  path: "/courses/",
  getParentRoute: () => rootRouteImport,
});
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: "/courses/$slug",
  path: "/courses/$slug",
  getParentRoute: () => rootRouteImport,
});
const LegalGuidelinesRoute = LegalGuidelinesRouteImport.update({
  id: "/legal/guidelines",
  path: "/legal/guidelines",
  getParentRoute: () => rootRouteImport,
});
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: "/legal/privacy",
  path: "/legal/privacy",
  getParentRoute: () => rootRouteImport,
});
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: "/legal/refunds",
  path: "/legal/refunds",
  getParentRoute: () => rootRouteImport,
});
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: "/legal/terms",
  path: "/legal/terms",
  getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EnrollRoute: EnrollRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LegalGuidelinesRoute: LegalGuidelinesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  CoursesIndexRoute: CoursesIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
