/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LegalGuidelinesRouteImport } from './routes/legal.guidelines'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalGuidelinesRoute = LegalGuidelinesRouteImport.update({
  id: '/legal/guidelines',
  path: '/legal/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enroll': typeof EnrollRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/guidelines': typeof LegalGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enroll': typeof EnrollRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/guidelines': typeof LegalGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enroll': typeof EnrollRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/guidelines': typeof LegalGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/enroll'
    | '/faq'
    | '/login'
    | '/plans'
    | '/courses/$slug'
    | '/legal/guidelines'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/enroll'
    | '/faq'
    | '/login'
    | '/plans'
    | '/courses/$slug'
    | '/legal/guidelines'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/enroll'
    | '/faq'
    | '/login'
    | '/plans'
    | '/courses/$slug'
    | '/legal/guidelines'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EnrollRoute: typeof EnrollRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LegalGuidelinesRoute: typeof LegalGuidelinesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/guidelines': {
      id: '/legal/guidelines'
      path: '/legal/guidelines'
      fullPath: '/legal/guidelines'
      preLoaderRoute: typeof LegalGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EnrollRoute: EnrollRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LegalGuidelinesRoute: LegalGuidelinesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
